FROM ruby:2.5.0

RUN apt-get update -qq && \
    apt-get install -y build-essential \
                       nodejs \
                       locales

ENV APP_PATH /rails_root

WORKDIR $APP_PATH

ADD Gemfile $APP_PATH
ADD Gemfile.lock $APP_PATH

RUN gem install bundler && bundle install --jobs 20 --retry 5 --without production --path vendor/bundle

# COPY package.json yarn.lock ./
# RUN yarn

COPY . APP_PATH

ENV TZ=Asia/Tokyo
RUN echo "${TZ}" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8
RUN localedef -f UTF-8 -i en_US en_US.utf8
