FROM node:8

RUN apt-get update -qq && \
    apt-get install -y gcc-4.9 \
                       libstdc++6
                       
ENV FRONTEND_PATH /frontend_root

WORKDIR $FRONTEND_PATH

ADD package.json $FRONTEND_PATH
ADD package-lock.json $FRONTEND_PATH

RUN npm install --quiet

COPY . $FRONTEND_PATH

EXPOSE 4200
